name: Support Request
description: Support request or question relating to Uno
labels: [triage/support]
body:
  - type: markdown
    attributes:
      value: |
        **STOP ⛔ -- PLEASE READ!**

        GitHub is not the right place for support requests.

        If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/uno-platform) and the [documentation](https://platform.uno/docs/).

        You can also post your question in [GitHub discussions](https://github.com/unoplatform/uno/discussions) or [on Twitter using the #unoplatform](https://twitter.com/search?q=%23unoplatform) hashtag.

        For organizations that want a deeper level of support beyond our community support, please [contact us](https://platform.uno/contact/). Our professional support is more than a contract – it is a shared responsibility for your project success. Our engineering team will collaborate with you to ensure the success of your projects, and our custom application development team at nventive is also available to lend its expertise.

        If the matter is security related, please disclose it privately via https://github.com/unoplatform/uno/security/

  - type: textarea
    id: support-request-text
    attributes:
      label: What do you need help with?
      description: If you still want to use GitHub Issues for Support request, you can do so bellow
